### ISSUE TITLE
It is not possible the exclude an entire class easily

### ISSUE THREAD

**Issue by nemeth-z** [GoodGrind/ghostwriter-api#5]
Currently the Exclude annotation cannot be placed on classes. In order to exclude a whole class, each method needs to be annotated. Furthermore if the class has a default constructor, it is explicitly need to be defined and excluded.
It would be really helpful if a class could be excluded by only putting the annotation on it.

**Comment by snorbi07** [comment]
The versions 0.3.1+ already contain the necessary changes to the annotation. This is a limitation in the instrumenter which is tracked by this ticket: https://github.com/GoodGrind/ghostwriter/issues/40
